List<String> predefinedSymptomsList = [
  'Runny or stuffy nose',
  'Sore throat',
  'Cough',
  'Congestion',
  'Slight body aches or a mild headache',
  'Sneezing',
  'Low-grade fever',
  'General feeling of being unwell',
  'Fever or feeling feverish/chills',
  'Muscle or body aches',
  'Headaches',
  'Fatigue (tiredness)',
  'Vomiting',
  'Diarrhea',
  'Shortness of breath or difficulty breathing',
  'New loss of taste or smell',
  'Nausea',
  'Increased thirst',
  'Frequent urination',
  'Extreme hunger',
  'Unexplained weight loss',
  'Presence of ketones in the urine',
  'Irritability',
  'Blurred vision',
  'Slow-healing sores',
  'Frequent infections',
  'Severe headache',
  'Vision problems',
  'Chest pain',
  'Irregular heartbeat',
  'Blood in the urine',
  'Pounding in your chest, neck, or ears',
  'Chest tightness or pain',
  'Wheezing when exhaling',
  'Trouble sleeping caused by shortness of breath, coughing, or wheezing',
  'Itching of the nose, eyes, or roof of the mouth',
  'Watery, red, or swollen eyes (conjunctivitis)',
  'Severe throbbing or pulsing pain, usually on one side of the head',
  'Sensitivity to light, sound, and sometimes smell and touch',
  'Lightheadedness, sometimes followed by fainting',
  'Watery, usually non-bloody diarrhea',
  'Abdominal cramps and pain',
  'Itchy rash that turns into fluid-filled blisters and eventually scabs over',
  'Loss of appetite',
  'Night sweats',
  'Persistent cough',
  'Coughing up blood',
  'Swollen lymph nodes',
  'Painful urination',
  'Cloudy or bloody urine',
  'Pelvic pain',
  'Back pain',
  'Neck stiffness',
  'Sensitivity to light',
  'Confusion',
  'Sleepiness',
  'Loss of consciousness',
  'Yellowing of the skin and eyes (jaundice)',
  'Dark urine',
  'Clay-colored stool',
  'Severe itching',
  'Easy bruising',
  'Swelling in the legs and abdomen',
  'Persistent fever',
  'Unintended weight loss',
  'Chills',
  'Sweating',
  'Malaise',
  'Persistent vomiting',
  'Dizziness',
  'Seizures',
  'Difficulty swallowing',
  'Persistent abdominal pain',
  'Constipation',
  'Gas and bloating',
  'Heartburn',
  'Rectal bleeding',
  'Unexplained skin rash',
  'Joint pain',
  'Muscle pain',
  'Difficulty moving a limb',
  'Persistent weakness or fatigue',
  'Difficulty concentrating',
  'Mood swings',
  'Persistent dry cough',
  'Hoarseness',
  'Swelling in the face or neck',
  'Rapid or irregular heartbeat',
  'Numbness or tingling in the hands or feet',
  'Dry mouth',
  'Persistent bad breath',
  'Sores in the mouth or on the lips',
  'Sudden weight gain',
  'Hair loss',
  'Changes in menstrual cycles',
  'Increased sensitivity to cold or heat',
  'High blood sugar levels',
  'Nausea or vomiting after eating fatty foods',
  'Difficulty breathing when lying down',
  'Unexplained bruising',
  'Skin that bruises easily',
  'Swelling of the ankles or legs',
  'Cravings for non-nutritive substances (pica)',
  'Persistent itching of the skin',
  'Difficulty urinating',
  'Changes in urine color',
  'Changes in skin color',
  'Pain in the upper right abdomen',
  'Persistent bloating',
  'Unexplained fever',
  'Persistent cough with mucus',
  'Bloody stools',
  'Persistent pain in the chest',
  'Fever or chills',
  'Fatigue',
  'Headache',
  'Congestion or runny nose',
  'Nausea or vomiting',
  'Bone pain',
  'Swelling or tenderness near a joint or bone',
  'Stiffness in the joints',
  'Limited range of motion',
  'Deformity of the affected bone or joint',
  'Fractures or breaks with minimal or no trauma',
  'Persistent back pain',
  'Difficulty standing or walking',
  'Weakness in the limbs',
  'Numbness or tingling in the extremities',
  'Chronic fatigue',
  'Bruising or discoloration around the affected area',
  'Noticeable bump or mass on a bone',
  'Redness or warmth over a bone or joint',
  'Difficulty performing daily activities due to pain or immobility',
  'Abdominal cramps',
  'Fever',
  'Muscle aches',
  'Dehydration',
  'Abdominal pain or cramps',
  'Bloating or gas',
  'Diarrhea or constipation',
  'Heartburn or indigestion',
  'Feeling of fullness or discomfort',
  'Blood in stool',
  'Stress',
  'Lack of sleep',
  'Hunger',
  'Eye strain',
  'Sinus infection',
  'Medication overuse',
  'Migraine',
  'Tension headache',
  'Cluster headache',
  'Ear pain',
  'Hearing loss',
  'Tinnitus (ringing in the ears)',
  'Vertigo',
  'Discharge from the ear',
  'Feeling of fullness in the ear',
  'Difficulty sleeping',
  'Pain during intercourse',
  'Loss of libido or sexual desire',
  'Erectile dysfunction',
  'Premature ejaculation',
  'Delayed ejaculation',
  'Vaginal dryness',
  'Abnormal discharge from the genital area',
  'Itching or irritation in the genital area',
  'Unusual bleeding or spotting',
  'Swelling or tenderness in the genital area',
  'Discomfort or pain in the pelvic region',
  'Difficulty achieving or maintaining an erection',
  'Reduced sexual pleasure',
  'Unusual or foul-smelling discharge',
  'Difficulty reaching orgasm',
  'Persistent sores, lumps, or bumps in the genital area',
  'Pain or discomfort in the testicles or penis',
  'Pain or discomfort in the vulva or vagina',
  'Loss of sexual arousal or sensation',
  'Involuntary leakage of semen or urine',
  'Sinusitis',
  'Allergies',
  'Common cold',
  'Flu',
  'Nasal polyps',
  'Deviated septum',
  'Dry air',
  'Foreign object in the nose',
  'Facial injury',
  'Dental problems',
  'Medications',
  'Exposure to irritants',
  'Thumb joint pain',
  'Thumb base pain',
  'Thumb tip pain',
  'Finger joint pain',
  'Fingertip pain',
  'Throbbing pain in thumb or finger',
  'Sharp pain in thumb or finger',
  'Dull ache in thumb or finger',
  'Stiffness in thumb or finger joints',
  'Swelling in thumb or finger',
  'Redness in thumb or finger',
  'Warmth in thumb or finger',
  'Weakness in thumb or finger',
  'Numbness in thumb or finger',
  'Tingling in thumb or finger',
  'Repetitive motion injury (e.g., typing, texting)',
  'Arthritis (e.g., osteoarthritis, rheumatoid arthritis)',
  'Tendinitis or tendonitis',
  'Carpal tunnel syndrome',
  'Trigger finger',
  'Injury (e.g., cut, sprain, fracture)',
  'Infection',
  'Nerve damage',
  'Other underlying medical conditions',
  'Vaginal itching or irritation',
  'Abnormal vaginal discharge',
  'Unusual odor from the vagina',
  'Vaginal bleeding or spotting between periods',
  'Swelling or tenderness in the vaginal area',
  'Persistent vaginal soreness or discomfort',
  'Burning sensation during urination',
  'Changes in the color or consistency of vaginal discharge',
  'Heavy or prolonged menstrual bleeding',
  'Sudden or unexplained changes in menstrual cycle',
  'Presence of lumps or bumps in the vaginal area',
  'Difficulty or pain when inserting tampons',
  'Frequent or recurring vaginal infections',
  'Pain in the lower abdomen or pelvis',
  'Excessive vaginal discharge',
  'Vaginal bleeding after menopause',
  'There is a persistent swelling or bulge in my breast area.',
  'Pain or tenderness',
  'Lump or mass',
  'Swelling or enlargement',
  'Unusual discharge from the nipple',
  'Changes in size or shape',
  'Redness or warmth',
  'Dimpled or puckered skin',
  'Inverted or turned inward nipple',
  'Persistent itching or rash',
  'Heavy or full sensation',
  'Change in skin texture',
  'Growing lump',
  'Unusually firm or hard breast',
  'Pain radiating to arm or shoulder',
  'Change in color or appearance of the nipple',
  'Blood-stained or clear discharge',
  'Frequent or severe pain unrelated to menstrual cycle',
  'Noticeable changes in contour',
  'Persistent swelling or bulge',
  'Excessive hair loss or thinning',
  'Bald patches or bald spots',
  'Unusual breakage or split ends',
  'Dry or brittle hair',
  'Oily or greasy hair',
  'Itchy or irritated scalp',
  'Redness or inflammation on the scalp',
  'Dandruff or flakes',
  'Change in hair texture',
  'Uneven hair growth',
  'Change in hair color without dye',
  'Scalp sensitivity or pain',
  'Hair falling out in clumps',
  'Slow hair growth',
  'Persistent scalp odor',
  'Hair loss with associated weight loss',
  'Excessive shedding during brushing or washing',
  'Unusual changes in hair volume',
  'Scalp sores or lesions',
  'Loss of hair along the hairline',
  'Rash',
  'Mouth sores or ulcers',
  'Weight loss',
  'Shortness of breath',
  'Unexplained tiredness',
  'Skin infections',
  'Recurrent infections',
  'Memory loss or confusion',
  'Nausea and vomiting',
  'Discomfort or pain in the chest',
  'Pain spreading to arms, neck, jaw, or shoulder',
  'Lightheadedness or dizziness',
  'Anxiety or restlessness',
  'Sore or painful mouth',
  'Mouth ulcers or sores',
  'Bleeding gums',
  'Swollen or inflamed gums',
  'Bad breath (halitosis)',
  'White or yellow patches on the tongue or inside the mouth',
  'Redness or swelling in the mouth or throat',
  'Change in taste or loss of taste',
  'Foul taste in the mouth',
  'Persistent mouth pain',
  'Cracked or chapped lips',
  'Gum recession',
  'Unusual lumps or bumps in the mouth',
  'Burning sensation in the mouth',
  'Loose or missing teeth',
  'Pain when chewing',
  'Mouth or jaw stiffness',
  'Persistent bad taste after eating',
  'Ache or dull pain',
  'Sharp, shooting pain',
  'Throbbing pain',
  'Burning sensation',
  'Numbness',
  'Tingling',
  'Sensitivity to touch',
  'Jaw pain',
  'Earache',
  'Eye pain',
  'Sinus pain',
  'Facial swelling',
  'Redness',
  'Difficulty opening mouth',
  'Muscle spasms',
  'Ache or soreness',
  'Sharp or stabbing pain',
  'Dull or throbbing pain',
  'Numbness or tingling',
  'Weakness in the hand',
  'Stiffness in the hand',
  'Swelling in the hand',
  'Redness in the hand',
  'Warmth in the hand',
  'Difficulty gripping or holding objects',
  'Pain when moving the hand or fingers',
  'Pain at rest',
  'Tenderness to touch',
  'Loss of dexterity',
  'Difficulty performing daily activities',
  'Abdominal cramps or pain',
  'Weakness or fatigue',
  'Stomach bloating',
  'Difficulty keeping food down',
  'Persistent stomachache',
  'Foul taste in mouth',
  'Dry mouth and throat',
  'Reduced urination',
  'Dark-colored urine',
  'Sudden onset of symptoms after eating',
  'Persistent sadness or low mood',
  'Excessive worry or anxiety',
  'Feeling overwhelmed or stressed',
  'Irritability or mood swings',
  'Difficulty concentrating or making decisions',
  'Changes in sleep patterns (insomnia or excessive sleeping)',
  'Loss of interest or pleasure in activities',
  'Feelings of hopelessness or helplessness',
  'Fatigue or low energy',
  'Social withdrawal or isolation',
  'Changes in appetite or weight',
  'Feeling disconnected from reality',
  'Experiencing hallucinations or delusions',
  'Thoughts of self-harm or suicide',
  'Memory problems or forgetfulness',
  'Difficulty managing emotions',
  'Unexplained physical symptoms with no medical cause',
  'Excessive anger or frustration',
  'Impulsivity or risky behavior',
  'Inability to perform daily tasks or responsibilities',
  'Chest pain or discomfort',
  'Palpitations or irregular heartbeat',
  'Pain radiating to the arm, jaw, or back',
  'Fainting or near-fainting',
  'Unexplained fatigue or weakness',
  'Swelling in the legs, ankles, or feet',
  'Rapid or slow heartbeat',
  'Persistent cough, especially with pink or frothy mucus',
  'Difficulty breathing while lying down',
  'Feeling of pressure or squeezing in the chest',
  'Sweating excessively',
  'Cold or clammy skin',
  'Unexplained swelling in the abdomen',
  'Pain in the upper back or shoulders',
  'Sudden or severe chest pain',
  'Irregular pulse or heartbeat',
  'Persistent or recurrent chest discomfort',
  'Jaundice (yellowing of the skin and eyes)',
  'Abdominal pain or tenderness',
  'Swelling or bloating in the abdomen',
  'Itchy skin',
  'Easy bruising or bleeding',
  'Enlarged liver (hepatomegaly)',
  'Swollen legs or ankles',
  'Persistent or severe itching',
  'Ascites (fluid buildup in the abdomen)',
  'Confusion or difficulty thinking clearly (hepatic encephalopathy)',
  'Foul breath (breath with a musty or sweet odor)',
  'Increased sensitivity to medications or alcohol',
  'Loss of muscle mass or strength',
  'Unexplained bleeding or bruising',
  'Frequent nosebleeds',
  'Excessive bleeding from minor cuts',
  'Persistent or heavy menstrual bleeding',
  'Unusual fatigue or weakness',
  'Paleness or jaundice (yellowing of the skin and eyes)',
  'Dizziness or lightheadedness',
  'Swelling in the legs or arms',
  'Blood in urine',
  'Black or tarry stools',
  'Persistent or severe headaches',
  'Feeling faint or dizzy',
  'Prolonged or excessive bleeding after surgery or dental work',
  'Frequent infections or illness',
  'Bruising easily',
  'Cold or numb extremities',
  'Nasal congestion or stuffiness',
  'Runny nose (rhinorrhea)',
  'Frequent or severe nosebleeds',
  'Loss of sense of smell (anosmia)',
  'Postnasal drip',
  'Nasal pain or tenderness',
  'Itchy nose',
  'Dryness inside the nose',
  'Facial pain or pressure',
  'Swelling around the nose or eyes',
  'Unusual nasal discharge (colored or foul-smelling)',
  'Nasal itching or irritation',
  'Frequent sinus infections',
  'Bleeding from the nose after minor trauma',
  'Crusting or scabs inside the nose',
  'A noticeable bump or deformity on the nose',
  'Difficulty breathing through the nose',
  'Hearing loss or ear fullness related to nasal issues',
  'Sore throat due to postnasal drip',
  'Anal itching or irritation',
  'Pain or discomfort around the anus',
  'Unusual discharge from the anus',
  'Hemorrhoids (swollen veins around the anus)',
  'Anal lumps or swelling',
  'Constipation or difficulty passing stools',
  'Cracked or fissured skin around the anus',
  'Feeling of incomplete bowel movement',
  'Persistent or severe abdominal pain',
  'Frequent urge to have a bowel movement',
  'Presence of mucus in stool',
  'Rectal prolapse (protrusion of the rectum through the anus)',
  'Involuntary leakage of stool or gas',
  'Change in bowel habits',
  'Itching or burning sensation during or after bowel movements',
  'Dark or tarry stools',
  'Pain during bowel movements',
  'fever',
  'cough',
  'fatigue',
  'headache',
  'sore throat',
  'runny nose',
  'shortness of breath',
  'muscle aches',
  'chills',
  'loss of taste',
  'loss of smell',
  'nausea',
  'vomiting',
  'diarrhea',
  'chest pain',
  'dizziness',
  'sweating',
  'weight loss',
  'weight gain',
  'abdominal pain',
  'rash',
  'itching',
  'joint pain',
  'swollen lymph nodes',
  'confusion',
  'blurred vision',
  'heart palpitations',
  'insomnia',
  'difficulty swallowing',
  'dry mouth',
  'hair loss',
  'hearing loss',
  'frequent urination',
  'night sweats',
  'tremors',
  'anxiety',
  'depression',
  'constipation',
  'bloody stool',
  'persistent cough',
  'lightheadedness',
  'bruising easily',
  'nosebleeds',
  'earache',
  'yellowing of the skin (jaundice)',
  'cold hands and feet',
  'increased thirst',
  'skin sores',
  'difficulty breathing',
  'hiccups',
  'hoarseness',
  'memory loss',
  'difficulty concentrating',
  'numbness',
  'tingling',
  'dry eyes',
  'mouth ulcers',
  'back pain',
  'red eyes',
  'excessive sweating',
  'swollen ankles',
  'difficulty urinating',
  'hallucinations',
  'slurred speech',
  'facial swelling',
  'blurred speech',
  'metallic taste',
  'irritability',
  'slow healing of wounds',
  'dry skin',
  'pale skin',
  'sensitivity to light',
  'ringing in the ears (tinnitus)',
  'excessive yawning',
  'loss of balance',
  'seizures',
  'bloating',
  'drooping eyelid',
  'double vision',
  'blood in urine',
  'painful urination',
  'excessive hunger',
  'difficulty walking',
  'weakness',
  'changes in appetite',
  'difficulty chewing',
  'muscle cramps',
  'restlessness',
  'unusual body odor',
  'eye twitching',
  'excessive blinking',
  'frequent infections',
  'loss of coordination',
  'swollen tongue',
  'paralysis',
  'night blindness',
  'frequent sighing',
  'hoarse voice',
  'chronic cough',
  'bitter taste',
  'excessive drooling',
  'hives',
  'spasms',
  'wheezing',
  'skin discoloration',
  'hair thinning',
  'slow pulse',
  'rapid pulse',
  'abnormal heartbeat',
  'unusual bleeding',
  'mouth dryness',
  'graying hair',
  'body aches',
  'joint stiffness',
  'pain in the flank',
  'dry scalp',
  'red skin patches',
  'chronic fatigue',
  'flushing',
  'hand tremors',
  'abdominal bloating',
  'acid reflux',
  'back stiffness',
  'belching',
  'blue lips',
  'burning sensation',
  'canker sores',
  'chest tightness',
  'clammy skin',
  'clumsiness',
  'cold intolerance',
  'cracked skin',
  'creaking joints',
  'crusting around the eyes',
  'dark urine',
  'dry nose',
  'ear discharge',
  'eye pain',
  'eye redness',
  'fainting',
  'fluid retention',
  'foul-smelling stool',
  'gasping for air',
  'grinding teeth',
  'hair breakage',
  'head pressure',
  'jaw pain',
  'muscle twitching',
  'nose twitching',
  'pink eye',
  'anal itching',
  'brittle nails',
  'burning eyes',
  'cheek swelling',
  'chills without fever',
  'clay-colored stool',
  'cloudy vision',
  'cramping',
  'decreased urine output',
  'delayed wound healing',
  'drooling',
  'fatty stools',
  'frequent belching',
  'frequent bruising',
  'frequent nosebleeds',
  'high blood pressure',
  'high fever',
  'hollowing eyes',
  'inability to sweat',
  'increased heart rate',
  'inflamed gums',
  'intestinal cramps',
  'leg cramps',
  'loss of appetite',
  'muscle wasting',
  'pale lips',
  'skin peeling',
  'slow wound healing',
  'sudden weight gain',
  'acidic taste in mouth',
  'ankle pain',
  'arm pain',
  'blistering skin',
  'bloodshot eyes',
  'bone pain',
  'chapped lips',
  'cold sweats',
  'creaky joints',
  'dehydration',
  'disorientation',
  'drooping face',
  'ear ringing',
  'excessive earwax',
  'facial twitching',
  'feeling cold',
  'feeling hot',
  'foot pain',
  'frequent headaches',
  'gagging',
  'groin pain',
  'hand pain',
  'hip pain',
  'inflamed tonsils',
  'jaw clenching',
  'knuckle pain',
  'knee pain',
  'laryngitis',
  'loose stools',
  'sensitive teeth',
  'abnormal body odor',
  'abnormal gait',
  'ankle swelling',
  'arm weakness',
  'black stool',
  'bloody cough',
  'blurred peripheral vision',
  'broken blood vessels',
  'bulging eyes',
  'burning scalp',
  'chest fluttering',
  'cracked heels',
  'dark circles under eyes',
  'delayed growth',
  'droopy eyelid',
  'ear fullness',
  'excessive salivation',
  'excessive thirst',
  'eye crust',
  'eyelid twitching',
  'finger pain',
  'foot swelling',
  'gag reflex',
  'gallbladder pain',
  'gassy stomach',
  'hand numbness',
  'hip stiffness',
  'hyperactivity',
  'inability to burp',
  'abdominal swelling',
  'abnormal muscle tone',
  'achy legs',
  'arm tingling',
  'ashy skin',
  'back rash',
  'blood in saliva',
  'blood in vomit',
  'blue nails',
  'bone swelling',
  'burning throat',
  'burst blood vessel in eye',
  'chest rash',
  'choking sensation',
  'collarbone pain',
  'decreased reflexes',
  'difficulty hearing',
  'dimpling of the skin',
  'drooping mouth',
  'enlarged liver',
  'facial numbness',
  'foot numbness',
  'gland swelling',
  'hand rash',
  'hip numbness',
  'hot flashes',
  'hunched posture',
  'jaw swelling',
  'neck stiffness',
  'nipple discharge',
  'abdominal tenderness',
  'anal pain',
  'arm rash',
  'back burning sensation',
  'bloating after meals',
  'blue skin',
  'brittle hair',
  'burning feet',
  'cheek numbness',
  'claw-like nails',
  'cold sores',
  'constant hunger',
  'dark patches on skin',
  'dry hair',
  'ear itching',
  'excessive body hair',
  'facial pain',
  'finger numbness',
  'fingernail ridges',
  'foot odor',
  'frequent yawning',
  'gurgling stomach',
  'head sweating',
  'joint redness',
  'lower back pain',
  'lower leg pain',
  'nail discoloration',
  'neck pain',
  'pelvic pain',
  'puffy eyes',
  'forehead pain',
  'forehead rash',
  'forehead swelling',
  'forehead tenderness',
  'forehead itching',
  'forehead redness',
  'forehead bruising',
  'forehead numbness',
  'forehead tingling',
  'forehead bumps',
  'forehead pimples',
  'forehead blisters',
  'forehead dry skin',
  'forehead oily skin',
  'forehead wrinkles',
  'forehead acne',
  'forehead discoloration',
  'forehead sunburn',
  'forehead scars',
  'forehead peeling',
  'forehead flaking',
  'forehead sweating',
  'forehead heat',
  'forehead cold sensation',
  'forehead tightness',
  'forehead cysts',
  'forehead lesions',
  'forehead cuts',
  'forehead burning sensation',
  'forehead muscle twitching',
  'ear pain',
  'ear swelling',
  'ear ringing (tinnitus)',
  'ear redness',
  'ear bleeding',
  'ear numbness',
  'ear tingling',
  'ear pressure',
  'ear infection',
  'ear warmth',
  'ear cold sensation',
  'ear burning sensation',
  'ear ache',
  'ear crusting',
  'ear popping',
  'ear clicking',
  'ear drainage',
  'ear congestion',
  'ear sores',
  'ear wax buildup',
  'ear odor',
  'ear blockage',
  'ear cysts',
  'ear lumps',
  'ear muscle twitching',
  'ear dryness',
  'ear ulcers',
  'skin rash',
  'rapid weight loss',
  'dry cough',
  'persistent tiredness',
  'white spots in the mouth',
  'red, brown, or purplish blotches on the skin',
  'numbness in the extremities',
  'blurry vision',
  'persistent nausea',
  'chronic pelvic pain',
  'menstrual irregularities',
  'yeast infections',
  'pneumonia',
  'neurological disorders',
  'recurring fever',
  'unexplained weight loss',
  'persistent fatigue',
  'pain',
  'skin changes',
  'changes in bowel habits',
  'persistent indigestion',
  'lump or thickening under the skin',
  'skin sores that do not heal',
  'white patches inside the mouth',
  'unusual bleeding or bruising',
  'persistent bloating',
  'persistent headache',
  'unexplained night sweats',
  'blood in stool',
  'persistent back pain',
  'changes in bladder habits',
  'chronic bone pain',
  'changes in a mole or wart',
  'persistent nausea or vomiting',
  'unexplained itching',
  'persistent abdominal pain',
  'jaundice (yellowing of the skin and eyes)',
  'unexplained shortness of breath',
  'unexplained weakness or numbness',
  'persistent chest pain',
  'persistent bone fractures',
  'persistent muscle weakness',
  'chronic infections',
  'persistent ear pain',
  'changes in taste or smell',
  'unexplained fever',
  'persistent sore throat',
  'difficulty moving',
  'changes in skin color',
  'unexplained skin rash',
  'persistent eye pain',
  'unusual discharge from any part of the body',
  'persistent joint pain',
  'persistent leg pain',
  'persistent neck pain',
  'difficulty speaking',
  'persistent hiccups',
  'unexplained hair loss',
  'new or unusual moles',
  'persistent itching in the genital or anal area',
  'persistent vaginal bleeding',
  'persistent or recurrent infections',
  'swollen face or neck',
  'persistent dry mouth',
  'persistent hoarseness',
  'unusual lumps or swelling in the breast or testicles',
  'pain in the penis',
  'swelling of the penis',
  'penile discharge',
  'itching on the penis',
  'redness of the penis',
  'penile sores',
  'penile lumps',
  'difficulty retracting foreskin',
  'rash on the penis',
  'penile blisters',
  'burning sensation in the penis',
  'blood in penile discharge',
  'erectile dysfunction',
  'painful erections',
  'penile curvature',
  'penile warts',
  'unusual odor from the penis',
  'penile ulcers',
  'numbness in the penis',
  'penile dryness',
  'pain during intercourse',
  'penile bruising',
  'peeling skin on the penis',
  'penile itching',
  'loss of sensation in the penis',
  'penile bleeding',
  'penile scarring',
  'difficulty ejaculating',
  'heartburn',
  'indigestion',
  'gas',
  'rectal bleeding',
  'persistent fullness',
  'jaundice',
  'pale stool',
  'fatty stool',
  'mucus in stool',
  'chronic stomach pain',
  'slow digestion',
  'burning sensation in stomach',
  'chronic bad breath',
  'difficulty passing stool',
  'early satiety',
  'epigastric pain',
  'fecal incontinence',
  'frequent hunger pangs',
  'gastritis',
  'gastrointestinal bleeding',
  'heartburn at night',
  'incomplete bowel movement',
  'intestinal obstruction',
  'liver pain',
  'lower abdominal pain',
  'malabsorption',
  'pain after eating',
  'persistent burping',
  'rectal prolapse',
  'slow bowel movements',
  'stomach growling',
  'stomach gurgling',
  'stomach ulcer',
  'vomiting blood',
  'redness',
  'swelling',
  'warmth at the infection site',
  'pus or discharge',
  'bad odor from the infection site',
  'blisters',
  'ulcers',
  'unexplained bruising',
  'excessive bleeding',
  'petechiae (small red spots on the skin)',
  'prolonged bleeding from cuts',
  'heavy menstrual periods',
  'anemia',
  'rapid heartbeat',
  'swelling in the legs',
  'persistent infections',
  'easy bruising',
  'headaches',
  'enlarged spleen',
  'blood clots',
  'flaky skin',
  'scaly skin',
  'acne',
  'eczema',
  'psoriasis',
  'dark spots',
  'light spots',
  'crusty patches',
  'oozing sores',
  'excessive hair growth',
  'nail ridges',
  'ingrown nails',
  'fungal infections',
  'skin thickening',
  'skin thinning',
  'sensitivity to sunlight',
  'stiffness',
  'swelling in joints',
  'reduced range of motion',
  'bone fractures',
  'osteoporosis',
  'brittle bones',
  'deformities',
  'curvature of the spine (scoliosis)',
  'loss of height',
  'warmth in joints',
  'joint instability',
  'limping',
  'muscle weakness',
  'joint locking',
  'joint deformity',
  'cracking sounds in joints',
  'numbness or tingling in limbs',
  'joint stiffness in the morning',
  'inflammation around joints',
  'loss of joint function',
  'pain that worsens with movement',
  'muscle pain',
  'muscle spasms',
  'muscle stiffness',
  'muscle inflammation',
  'muscle fatigue',
  'muscle tenderness',
  'difficulty lifting objects',
  'difficulty climbing stairs',
  'loss of muscle mass',
  'reduced muscle tone',
  'reduced grip strength',
  'muscle rigidity',
  'slow reflexes',
  'muscle knots',
  'limited range of motion',
  'muscle tightness',
  'muscle swelling',
  'delayed muscle recovery',
  'muscle tearing',
  'muscle bruising',
  'difficulty standing up',
  'difficulty sitting down',
  'involuntary movements',
  'muscle soreness',
  'muscle atrophy',
  'persistent muscle contractions',
  'muscle twitching under the skin',
  'generalized weakness',
  'muscle fibrillation',
  'muscle bulging',
  'muscle tenderness to touch',
  'weak grip',
  'shuffling gait',
  'post-exertional malaise',
  'weakness in specific muscles',
  'pain with movement',
  'muscle deformity',
  'difficulty with fine motor skills',
  'recurrent muscle injuries',
  'muscle hardness',
  'muscle burning sensation',
  'frequent falls',
  'vertigo',
  'balance problems',
  'partial or complete paralysis',
  'difficulty understanding language',
  'mood swings',
  'delusions',
  'chronic pain',
  'neuropathic pain',
  'electric shock sensations',
  'sensitivity to touch',
  'sensitivity to sound',
  'excessive sleepiness',
  'sleep disturbances',
  'loss of bladder control',
  'loss of bowel control',
  'sexual dysfunction',
  'spasticity',
  'rigidity',
  'resting tremor',
  'postural instability',
  'bradykinesia (slowness of movement)',
  'dyskinesia (abnormal movements)',
  'autonomic dysfunction',
  'cold flashes',
  'palpitations',
  'irregular heartbeat',
  'slow heartbeat',
  'swelling in the ankles',
  'swelling in the feet',
  'swelling in the abdomen',
  'persistent coughing',
  'low blood pressure',
  'pain in the neck',
  'pain in the jaw',
  'pain in the throat',
  'pain in the upper abdomen',
  'pain in the back',
  'pain in the arms',
  'pain in the shoulders',
  'cold hands',
  'cold feet',
  'bluish skin',
  'trouble concentrating',
  'unexplained weight gain',
  'frequent urination at night',
  'coughing up blood',
  'reduced exercise tolerance',
  'claudication (pain in legs with walking)',
  'skin ulcers',
  'varicose veins',
  'syncope (temporary loss of consciousness)',
  'cyanosis (bluish discoloration of the skin)',
  'orthopnea (shortness of breath when lying flat)',
  'paroxysmal nocturnal dyspnea (severe shortness of breath at night)',
  'hemoptysis (coughing up blood)',
  'irregular pulse',
  'feeling of impending doom',
  'enlarged lymph nodes',
  'tender lymph nodes',
  'painful lymph nodes',
  'recurrent infections',
  'itchy skin',
  'red patches on skin',
  'swelling in arms',
  'swelling in legs',
  'swelling in abdomen',
  'pain in the abdomen',
  'sinus congestion',
  'fluid buildup in lungs',
  'spleen enlargement',
  'liver enlargement',
  'sensitivity to cold',
  'general malaise',
  'unexplained sweating',
  'abdominal distension',
  'persistent mucus production',
  'frequent respiratory infections',
  'noisy breathing',
  'rapid breathing',
  'slow breathing',
  'shallow breathing',
  'bluish lips',
  'bluish fingernails',
  'snoring',
  'stridor (high-pitched breathing sound)',
  'loss of voice',
  'post-nasal drip',
  'nasal congestion',
  'sneezing',
  'sinus pain',
  'sinus pressure',
  'difficulty sleeping',
  'sleep apnea',
  'waking up gasping for air',
  'recurrent pneumonia',
  'recurrent bronchitis',
  'pleuritic chest pain (pain with breathing)',
  'crackles (rales)',
  'rhonchi',
  'clubbing of fingers',
  'bad breath',
  'chronic sinusitis',
  'allergic reactions',
  'itchy throat',
  'swollen tonsils',
  'coughing at night',
  'chronic ear infections',
  'nasal polyps',
  'wheezing after exercise',
  'abnormal vaginal bleeding',
  'painful periods',
  'irregular menstrual cycles',
  'missed periods',
  'painful intercourse',
  'vaginal discharge',
  'vaginal itching',
  'vaginal dryness',
  'vaginal odor',
  'vaginal swelling',
  'vaginal sores',
  'bleeding after intercourse',
  'lumps in the breast',
  'breast pain',
  'nipple inversion',
  'swollen lymph nodes in armpits',
  'pain in the lower abdomen',
  'incontinence',
  'pelvic pressure',
  'infertility',
  'painful ejaculation',
  'blood in semen',
  'testicular pain',
  'testicular swelling',
  'testicular lumps',
  'penile pain',
  'scrotal pain',
  'scrotal swelling',
  'reduced libido',
  'premature ejaculation',
  'delayed ejaculation',
  'painful menstruation',
  'ovarian pain',
  'pelvic inflammatory disease',
  'increased hunger',
  'sensitivity to heat',
  'delayed puberty',
  'early puberty',
  'stunted growth',
  'excessive growth',
  'fractures',
  'swelling in the neck',
  'goiter',
  'excessive appetite',
  'shaking hands',
  'unexplained weight changes',
  'unexplained fatigue',
  'oily skin',
  'skin rashes',
  'reduced sweating',
  'body odor',
  'persistent itching',
  'pus-filled blisters',
  'tearing',
  'eye irritation',
  'mouth sores',
  'swollen salivary glands',
  'painful salivary glands',
  'enlarged salivary glands',
  'coughing up mucus',
  'thick mucus',
  'blocked nasal passages',
  'chronic sinus infections',
  'frequent lung infections',
  'greasy stools',
  'poor growth',
  'pale stools',
  'salty-tasting skin',
  'dry nasal passages',
  'frequent ear infections',
  'sunburn',
  'freckles',
  'moles',
  'skin tags',
  'warts',
  'stretch marks',
  'cellulite',
  'spider veins',
  'bruising',
  'calluses',
  'corns',
  'blotchy skin',
  'pimples',
  'blackheads',
  'whiteheads',
  'dermatitis',
  'rosacea',
  'hyperpigmentation',
  'hypopigmentation',
  'skin lesions',
  'pustules',
  'nodules',
  'cysts',
  'wrinkles',
  'age spots',
  'inflammation',
  'autoimmune reactions',
  'stiff joints',
  'swollen joints',
  'tenderness in bones or joints',
  'frequent fractures',
  'weak bones',
  'decreased bone density',
  'spinal deformity',
  'stooped posture',
  'clicking joints',
  'grating sensation in joints',
  'bone spurs',
  'joint stiffness after inactivity',
  'pain during movement',
  'swelling in limbs',
  'limited flexibility',
  'reduced mobility',
  'difficulty gripping objects',
  'loss of grip strength',
  'painful swelling',
  'bone deformities',
  'osteopenia',
  'arthritis',
  'rheumatoid arthritis',
  'osteoarthritis',
  'scoliosis',
  'kyphosis',
  'lordosis',
  'difficulty bending',
  'bone infections',
  'joint infections',
  'crepitus (crackling or popping sound in joints)',
  'difficulty performing daily activities',
  'pain worsening at night',
  'restless legs',
  'reduced bone mass',
  'urgent need to urinate',
  'burning sensation during urination',
  'cloudy urine',
  'foul-smelling urine',
  'difficulty starting urination',
  'weak urine stream',
  'dribbling at the end of urination',
  'incomplete emptying of bladder',
  'nocturia (frequent urination at night)',
  'urinary incontinence',
  'urinary retention',
  'flank pain',
  'pain in the bladder area',
  'pain in the urethra',
  'swelling in the lower abdomen',
  'difficulty passing urine',
  'frequent urinary tract infections (UTIs)',
  'recurrent UTIs',
  'unusual discharge',
  'bladder spasms',
  'feeling of pressure in the lower abdomen',
  'urinary urgency without passing much urine',
  'passing small amounts of urine',
  'urinary hesitancy',
  'straining to urinate',
  'foamy urine',
  'pain in the sides',
  'kidney pain',
  'cramps',
  'chronic kidney disease',
  'renal colic',
  'kidney stones',
  'urethral discharge',
  'pain that comes in waves',
  'frequent urge to urinate with little urine output',
  'brain fog',
  'prolonged fatigue',
  'recurrent fever',
  'persistent headaches',
  'congestion',
  'discoloration of fingers or toes',
  'blisters on the skin',
  'light sensitivity',
  'tinnitus (ringing in the ears)',
  'memory problems',
  'persistent sinus congestion',
  'swelling in extremities',
  'blue lips or face',
  'difficulty breathing while lying down',
  'chronic fatigue syndrome',
  'long COVID symptoms',
  'COVID-19 reinfection',
  'persistent dry cough',
  'COVID toes',
  'post-viral fatigue',
  'autoimmune flare-ups',
  'cytokine storm',
  'persistent loss of smell',
  'persistent loss of taste',
  'COVID-19 related myocarditis',
  'multisystem inflammatory syndrome',
  'neuropathy',
  'paresthesia (tingling or numbness)',
  'brain inflammation',
  'encephalopathy',
  'acute respiratory distress syndrome (ARDS)',
  'thromboembolism',
  'silent hypoxia',
  'COVID-19 related skin manifestations',
  'Gastrointestinal symptoms related to COVID-19',
  'COVID-19 related hair loss',
  'post-vaccination side effects',
  'vaccine breakthrough infections',
  'reactivation of latent infections',
  'mental health issues related to pandemic stress',
  'increased substance abuse',
  'pandemic-related sleep disorders',
  'increased anxiety',
  'increased depression',
  'quarantine fatigue',
  'screen time-related eye strain',
  'zoom fatigue',
  'increased sedentary behavior',
  'weight gain during lockdown',
  'increased muscle tension',
  'chronic back pain from remote work setups',
  'pandemic-related PTSD',
  'social isolation effects',
  'COVID-19 related kidney damage',
  'persistent headaches post-COVID',
  'changes in menstrual cycle post-COVID',
  'post-viral arthritis',
  'exercise intolerance',
  'heart palpitations post-infection',
  'persistent sore throat post-COVID',
  'post-COVID sleep disturbances',
  'olfactory hallucinations (phantosmia)',
  'gustatory hallucinations',
  'COVID-19 related mental fog',
  'new onset allergies',
  'post-viral diabetes',
  'post-COVID balance issues',
  'post-COVID swallowing difficulties',
  'COVID-19 related liver inflammation',
  'skin sensitivity',
  'new food intolerances post-COVID',
  'persistent chills',
  'COVID-19 related muscle twitching',
  'increased susceptibility to colds',
  'persistent runny nose post-infection',
  "Eye pain",
  "hives",
  "rash",
  "bruises"
];
